pluginManagement {
    repositories {
        mavenCentral()
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
        gradlePluginPortal()
    }
}

plugins {
    // Позволяет Gradle самому скачать JDK 21, если в системе его нет.
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'GimpanumMod'
